AWSTemplateFormatVersion: '2010-09-09'
Description: Bucket S3 para almacenar artefactos de Lambda

Parameters:
  BucketName:
    Type: String
    Description: Nombre del bucket S3

Resources:
  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Nombre del bucket creado
    Value: !Ref LambdaArtifactsBucket
